In [1]:
import numpy as np
np.version.version

'1.16.5'

In [2]:
#!pip install numpy

In [4]:
#old method
sales =[4356,4543,3323,4433]
profit =[543,322,433,455]
profitratio =[]
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.1246556473829201,
 0.07087827426810478,
 0.13030394222088473,
 0.10263929618768329]

In [5]:
sales_array = np.array(sales)


In [6]:
profit_array = np.array(profit)

In [7]:
profit_array/sales_array

array([0.12465565, 0.07087827, 0.13030394, 0.1026393 ])

In [10]:
import time
size = 1000000
l1 =range(size)
l2 =range(size)
A1 =np.arange(size)
A2 =np.arange(size)
start = time.time()
result =[(x,y) for x,y in zip(l1,l2)]
print('Time taken by the list')
print((time.time()-start)*1000)

start = time.time()
result =A1+A2
print('Time taken by arrays')
print((time.time()-start)*1000)


Time taken by the list
382.26842880249023
Time taken by arrays
65.04654884338379


In [11]:
sales*3

[4356, 4543, 3323, 4433, 4356, 4543, 3323, 4433, 4356, 4543, 3323, 4433]

In [12]:
sales_array*3

array([13068, 13629,  9969, 13299])

In [19]:
list = [20,25.5,True]
type(list[2])

bool

In [23]:
np.array(list)

array([20. , 25.5,  1. ])

In [22]:
type(np.array(list)[2])

numpy.float64

In [24]:
list1 = [0,1,2,3,4,5,6,7,8]
list2 = list1.copy()

In [25]:
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [27]:
list2[0]=10

In [28]:
list2

[10, 1, 2, 3, 4, 5, 6, 7, 8]

In [29]:
list3 =list1[0:6]

In [30]:
list3[0]=20

In [31]:
list3

[20, 1, 2, 3, 4, 5]

In [34]:
list4=list1

In [35]:
list4[0]=10

In [39]:
id(list4)

957383314824

In [38]:
id(list1)

957383314824

In [40]:
array1 = np.array(list1)


In [41]:
array2 = array1.copy()

In [42]:
array1

array([10,  1,  2,  3,  4,  5,  6,  7,  8])

In [43]:
array2[0]=100

In [44]:
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8])

In [45]:
array3 =array1[0:6]

In [46]:
array1

array([10,  1,  2,  3,  4,  5,  6,  7,  8])

In [47]:
array3[0]=100

In [48]:
array3

array([100,   1,   2,   3,   4,   5])

In [49]:
array4=array1

In [50]:
array4[0]=1000

In [51]:
sales_us =[4322,4553,7654,6542]
sales_eu =[6554,8866,2223,2222]
sales_jp =[2334,7655,7655,8755]
sales_matrix=np.array([sales_us,sales_eu,sales_jp])

In [53]:
type(sales_matrix)

numpy.ndarray

In [54]:
sales_matrix

array([[4322, 4553, 7654, 6542],
       [6554, 8866, 2223, 2222],
       [2334, 7655, 7655, 8755]])

In [55]:
profit_us = [543 ,223,233,322]
profit_eu = [563 ,123,333,372]
profit_jp = [503 ,263,253,392]


In [ ]:
profit_matrix=np.array([profit_us,profit_eu,profit_])

In [58]:
profit_matrix/sales_matrix

array([[0.12563628, 0.0489787 , 0.0304416 , 0.04922042],
       [0.08590174, 0.01387322, 0.14979757, 0.16741674],
       [0.21550985, 0.03435663, 0.03305029, 0.04477441]])

In [60]:
sales_matrix[1,2]

2223

In [61]:
sales_matrix

array([[4322, 4553, 7654, 6542],
       [6554, 8866, 2223, 2222],
       [2334, 7655, 7655, 8755]])

In [62]:
sales_matrix[2:4,0:3]

array([[2334, 7655, 7655]])

In [63]:
sales_matrix

array([[4322, 4553, 7654, 6542],
       [6554, 8866, 2223, 2222],
       [2334, 7655, 7655, 8755]])

In [64]:
rdict ={'US':0,'EU':1, 'JP':2}
qdict ={'Q1' :0, 'Q2':1, 'Q3':2 ,'Q4':3}

In [65]:
sales_matrix[rdict['US']][qdict['Q3']]

7654

In [66]:
sales_matrix[0][2]

7654

In [67]:
a=np.arange(0,20)

In [68]:
np.reshape(a,(4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
np.reshape(a,(4,5), 'C') 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
list1 =[1,2,3,4]
list2 =[5,6,7,8]
a1 =np.array(list1)
a2 =np.array(list2)

In [71]:
a1

array([1, 2, 3, 4])

In [72]:
a2

array([5, 6, 7, 8])

In [73]:
np.add(a1,a2)

array([ 6,  8, 10, 12])

In [75]:
np.subtract(a1,a2)

array([-4, -4, -4, -4])

In [77]:
np.multiply(a1,a2)

array([ 5, 12, 21, 32])

In [78]:
np.divide(a1,a2)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [79]:
np.power(a1,a2)

array([    1,    64,  2187, 65536], dtype=int32)

In [83]:
np.median(a1)

2.5

In [84]:
np.mean(a1)

2.5

In [85]:
a1

array([1, 2, 3, 4])

In [86]:
np.average(a1)

2.5

In [87]:
np.std(a1)

1.118033988749895

In [88]:
np.var(a1)

1.25

In [89]:
np.cumsum(a1)

array([ 1,  3,  6, 10], dtype=int32)

In [90]:
a1

array([1, 2, 3, 4])